finAI/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from api import views

router = DefaultRouter()
router.register(r'account',views.AccountViewSet)
router.register(r'coin',views.CoinViewSet)
router.register(r'balance',views.BalanceViewSet)
router.register(r'tradehistory',views.TradeHistoryViewSet)

urlpatterns = [
    path('admin/', admin.site.urls),
    # path('', include('trading_simulator.urls')),
    path('', include('main.urls')),
    path('trading_simulator/', include('trading_simulator.urls')),
    path('api/', include(router.urls)),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'website'

urlpatterns = [
    path('', views.index, name='index'),
]

trading_simulator/urls.py
from django.urls import path
from . import views

app_name = "trading_simulator"

urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name="create"),
    path('deposit/<int:id>', views.deposit, name="deposit"),
    path('login/', views.login, name="login"),
    path('balances/<int:id>', views.balances, name="balances"),
    path('trading/<int:id>', views.trading, name="trading"),
    path('trade/', views.trade),
    path('logout/', views.logout),
    path('getBalance/', views.getBalance),
    path('getCoins/', views.getCoins),
    path('getCoinBalance/<int:coinId>/', views.getCoinBalance),
    path('getCMCcoin/', views.getCMCcoin),
    path('getCryptoNews/', views.getCryptoNews),
    path('getTop100/', views.getTop100),
    path('top100/', views.top100),
    path('validateEmail', views.validateEmail),
    path('admin/', views.admin_index)
]

trading_simulator/models.py
from django.db import models

# Create your models here.
class account(models.Model):
    accountId = models.AutoField(primary_key=True)
    email = models.EmailField()
    password = models.CharField(max_length=20)
    name = models.CharField(max_length=40)
    initialAmount = models.FloatField(default=0)
    isAdmin = models.BooleanField(default=False)

    class Meta:
        db_table = 'accounts'

class coin(models.Model):
    coinId = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    symbol = models.CharField(max_length=10)
    cmcId = models.IntegerField()

    class Meta:
        db_table = 'coins'

class balance(models.Model):
    accountId = models.ForeignKey(account, models.CASCADE, db_column='accountId')
    coinId = models.ForeignKey(coin, models.CASCADE, db_column='coinId')
    coinBalance = models.FloatField()

    class Meta:
        db_table = 'balances'
        unique_together = ('accountId', 'coinId')

class tradeHistory(models.Model):
    tradeId = models.AutoField(primary_key=True)
    coinId = models.ForeignKey(coin,models.CASCADE,db_column='coinId')
    accountId = models.ForeignKey(account,models.CASCADE,db_column='accountId')
    tradeType = models.CharField(max_length=10)
    amount = models.FloatField()
    price = models.FloatField()
    date = models.DateTimeField()

    class Meta:
        db_table = 'trade_history'

trading_simulator/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from trading_simulator.models import account, balance, tradeHistory, coin
from django.core import serializers
from bs4 import BeautifulSoup
import datetime, requests, json

# Create your views here.
def index(request):
    return render(request, 'trading_simulator/index.html')

def create(request):
    if request.method == 'POST':
        name = request.POST['name']
        email = request.POST['email']
        password = request.POST['password']
        initial = float(request.POST['initial'])

        account.objects.create(name=name, email=email, password=password, initialAmount=initial)
        balance.objects.create(accountId=account.objects.get(email=email),
                                coinId=coin.objects.get(coinId=1),
                                coinBalance=initial)
        
        return redirect('/trading_simulator/login/')

    return render(request, 'trading_simulator/create.html')

def validateEmail(request):
    if request.method == 'GET':
        email = request.GET['email']
        email_in_db = serializers.serialize("json", account.objects.filter(email=email))
    return HttpResponse(email_in_db, content_type="application/json")

def deposit(request, id):
    balance_ = balance.objects.get(accountId=id)

    if request.method == 'POST':
        USDbalance = request.POST['usd']
        BTCbalance = request.POST['btc']

        balance_.USDbalance = USDbalance
        balance_.BTCbalance = BTCbalance
        balance_.save()

        return redirect('/')

    return render(request, 'trading_simulator/deposit.html', locals())

def login(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        account_ = account.objects.filter(email=email, password=password)

        if account_ and not account_[0].isAdmin:
            # login success
            print('success')
            account__ = account.objects.get(email=email, password=password)

            # session
            request.session['id'] = account__.accountId

            response = HttpResponse('login success...<script>location.href="/trading_simulator/balances/{}"</script>'.format(account__.accountId))
            response.set_cookie("email", email)
            response.set_cookie("accountId", account__.accountId)
            return response

        elif account_ and account_[0].isAdmin:
            print('admin login')
            account__ = account.objects.get(email=email, password=password)

            # session
            request.session['id'] = account__.accountId

            return HttpResponse('admin login success...<script>location.href="/trading_simulator/admin/"</script>')

        else:
            # login fail
            print('fail')
            return HttpResponse('<script>alert("login failed...try again");location.href="/trading_simulator/login/";</script>')

    return render(request, 'trading_simulator/login.html')

def balances(request, id):
    if 'id' in request.session:
        accountId = request.session['id']

        account_ = account.objects.get(accountId=id)
        balance_ = balance.objects.filter(accountId=id)
        coin_ = coin.objects.all()
        tradeHistory_ = tradeHistory.objects.filter(accountId=id)

        return render(request, 'trading_simulator/showbalance.html', locals())
    else:
        return redirect('/trading_simulator/login/')

def trading(request, id):
    if 'id' in request.session:
        return render(request, 'trading_simulator/trade.html', locals())
    else:
        return redirect('/trading_simulator/login/')

def trade(request):
    if request.method == 'POST':
        accountId = request.session['id']
        price = request.POST['price']
        amount = request.POST['amount']
        type_ = request.POST['type']
        coinId = request.POST['coinId']

        print("PRICE = " + price)
        print("AMOUNT = " + amount)
        print("ACCOUNT ID = " + "{}".format(accountId))
        print("TYPE = " + type_)
        print("COIN ID = " + coinId)

        usd_balance = balance.objects.filter(accountId=accountId).get(coinId=1)
        coin_balance = balance.objects.filter(accountId=accountId).filter(coinId=coinId)
        total = float(price) * float(amount)

        successfulTransaction = False

        if coin_balance:
            print("already have this coin")
            
            if type_.lower() == 'buy':
                if total <= usd_balance.coinBalance and total > 0:
                    print("have enough money to buy: " + str(usd_balance.coinBalance))
                    usd_balance.coinBalance -= float(total)
                    coin_balance[0].coinBalance += float(amount)
                    print("new usd balance: " + str(usd_balance.coinBalance))
                    print("new coin balance: " + str(coin_balance[0].coinBalance))
                    successfulTransaction = True

            elif type_.lower() == 'sell':
                print("have enough to sell: " + str(coin_balance[0].coinBalance))
                if 0 < float(amount) <= coin_balance[0].coinBalance:
                    coin_balance[0].coinBalance -= float(amount)
                    usd_balance.coinBalance += total
                    print("new usd balance: " + str(usd_balance.coinBalance))
                    print("new coin balance: " + str(coin_balance[0].coinBalance))
                    successfulTransaction = True

            usd_balance.save()
            coin_balance[0].save()
            
        else:
            print("don't have this coin")

            if type_.lower() == 'buy':
                if total <= usd_balance.coinBalance and total > 0:
                    print("have enough money to buy: " + str(usd_balance.coinBalance))
                    usd_balance.coinBalance -= float(total)
                    balance.objects.create(accountId=account.objects.get(accountId=accountId),
                                            coinId=coin.objects.get(coinId=coinId),
                                            coinBalance=amount)
                    successfulTransaction = True
                    usd_balance.save()

        # write to trade history table
        if successfulTransaction:
            print("writing to trade history...")
            tradeHistory.objects.create(tradeType=type_,
                                    amount=float(amount),
                                    price=float(price),
                                    date=datetime.datetime.now(),
                                    accountId=account.objects.get(accountId=accountId),
                                    coinId=coin.objects.get(coinId=coinId))

            response = HttpResponse('success')

        else:
            response = HttpResponse('failed')

        return response

def logout(request):
    response = HttpResponse("<script>location.href='/trading_simulator/'</script>")
    response.delete_cookie('accountId')
    response.delete_cookie('email')
    
    request.session.clear()

    return response

def top100(request):
    return render(request, 'trading_simulator/top100.html', locals())

def getBalance(request):
    accountId = request.session['id']
    balance_ = serializers.serialize("json", balance.objects.filter(accountId=accountId).exclude(coinBalance=0))
    account_ = serializers.serialize("json", account.objects.filter(accountId=accountId))
    tradeHistory_ = serializers.serialize("json", tradeHistory.objects.filter(accountId=accountId))

    data = {'account':json.loads(account_), 
            'balances':json.loads(balance_), 
            'trades':json.loads(tradeHistory_)}
    datastr = json.dumps(data)

    return HttpResponse(datastr, content_type="application/json")

def getCoins(request):
    coin_ = serializers.serialize("json", coin.objects.all())

    return HttpResponse(coin_, content_type="application/json")

def getCoinBalance(request, coinId):
    accountId = request.session['id']
    balance_ = serializers.serialize("json", balance.objects.filter(accountId=accountId).filter(coinId=coinId))
    return HttpResponse(balance_, content_type="application/json")

def getCMCcoin(request):
    if request.method == 'GET':
        request_url = 'https://api.coinmarketcap.com/v2/ticker/'
        if 'ticker' in request.GET:
            ticker = request.GET['ticker']
            request_url += ticker +'/'
            r = requests.get(request_url)
            return JsonResponse(r.json())

        else:
            return JsonResponse(requests.get(request_url).json())

def getCryptoNews(request):
    url = 'https://www.ccn.com/'

    header = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36'
    }

    response = requests.get(url, headers=header)
    soup = BeautifulSoup(response.text, "lxml")

    article_list = []
    articles = soup.select('.page-content .posts-row article')
    for article in articles:
        article_title = article.find('header').find('h4', class_="entry-title").find('a').string
        article_link = article.find('header').find('h4', class_="entry-title").find('a').get('href')
        article_image = article.find('div', class_='post-thumbnail').find('img').get('src')
        article_date = article.find('header').find(class_="updated").get('datetime')
        article_list.append({"title":article_title, "link":article_link, "img":article_image, "time":article_date})
        # print(article_title)
        # print(article_link)
        # print(article_image)
        # print(article_date)
        # print('')

    articles_ = {"articles":article_list}
    # articles_ = json.dumps(articles_)
    # print(articles_)
    return JsonResponse(articles_)

def getTop100(request):
    url = 'https://coinmarketcap.com/'

    header = {

trading_simulator/templates/trading_simulator/admin.html
{% extends 'base.html' %}
{% block content %}
<style>
#btnToTop {
  height: 50px;
  width: 50px;
  display: none;
  position: fixed;
  bottom: 20px;
  right: 30px;
  z-index: 99;
  font-size: 18px;
  border: none;
  outline: none;
  background-color: red;
  color: white;
  cursor: pointer;
  padding: 15px;
  border-radius: 4px;
}

#btnToTop:hover {
  background-color: #555;
}
</style>

<button id="btnToTop" title="Go to top"><i class="fas fa-caret-up"></i></button>

<div class="container">
    <div class="row text-left" style="margin:100px 0;">
        <div class="col">
            <h1 class="display-4">Admin Panel</h1>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="#coin">Coins</a></li>
                    <li class="breadcrumb-item"><a href="#account">Accounts</a></li>
                    <li class="breadcrumb-item active"><a href="/trading_simulator/logout/">Logout</a></li>
                </ol>
            </nav>
        </div>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col">
            <h2 class="display-4"><a id="coin">Coins</a></h2>
        </div>
    </div> 
    <hr>
    <div class="row align-items-start">
        <div class="col"> 
            <h2 id="coinListTitle">Coin List</h2>
            <table class="table table-bordered" id="coinList">
                <thead class="bg-primary text-white">
                    <th>coinId</th>
                    <th>name</th>
                    <th>symbol</th>
                    <th>cmcId</th>
                    <th>delete</th>
                </thead>
                <tbody>
                </tbody>
            </table>     
        </div>
        <div class="col">
            <h2>Add Coin</h2>
            <table class="table table-bordered" id="coinAdd">
                <thead class="bg-primary text-white">
                    <th>coin list</th>
                    <th>name</th>
                    <th>symbol</th>
                    <th>cmcId</th>
                    <th>add</th>
                </thead>
                <tbody>
                    <td><select class="form-control" id="cmcCoinList"></select></td>
                    <td>name</td>
                    <td>symbol</td>
                    <td>cmcId</td>
                    <td><button id="btnAddCoin" class="btn btn-success"><i class="fas fa-plus"></i></button></td>
                </tbody>
            </table>
        </div>
    </div>
</div>
<br>
<div class="container">
    <div class="row">
        <div class="col">
            <h2 class="display-4"><a id="account">Accounts</a></h2>
        </div>
    </div> 
    <hr>
    <div class="row align-items-start">
        <div class="col"> 
            <h2 id="accountListTitle">Account List</h2>
            <table class="table table-bordered" id="accountList">
                <thead class="bg-primary text-white">
                    <th>accountId</th>
                    <th>name</th>
                    <th>email</th>
                    <th>edit/delete</th>
                </thead>
                <tbody>
                </tbody>
            </table>     
        </div>
    </div>
</div>
<div class="container">
    <div class="row" style="margin-bottom: 100px">
        <div class="col">
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    var coinList = [];
    function getCoins(){
        coinList = [];
        $.ajax({
            method: 'GET',
            url: '/api/coin/'
        }).done(function(msg){
            console.log(msg);
            $('#coinListTitle').text(`Coin List (${msg.length} coins total)`);
            var docFrag = $(document.createDocumentFragment());
            $.each(msg, function(index, coin){
                if(coin.cmcId != 0) {
                    var row = $('<tr></tr>');
                    var coinId = $('<td></td>').html(coin.coinId);
                    var name = $('<td></td>').html(coin.name);
                    var symbol = $('<td></td>').html(coin.symbol);
                    var cmcId = $('<td></td>').html(coin.cmcId);
                    var edit = $('<td></td>').html('<button class="btnDeleteCoin btn btn-danger"><i class="fas fa-trash"></i></button>');
                    row.append([coinId, name, symbol, cmcId, edit]);
                    docFrag.append(row);
                    coinList.push(coin.cmcId);
                }
            });
            $('#coinList tbody').html(docFrag);
            $('#coinAdd tbody td:nth-child(2)').text('');
            $('#coinAdd tbody td:nth-child(3)').text('');
            $('#coinAdd tbody td:nth-child(4)').text('');

            getCMCCoins();
        });
    }
    getCoins();

    function getCMCCoins(){
        $.ajax({
            method: 'GET',
            url: '/trading_simulator/getCMCcoin/'
        }).done(function(msg){
            console.log(msg);
            var docFrag = $(document.createDocumentFragment());            
            $.each(msg.data, function(index, coin){
                if(!(coinList.includes(coin.id))){
                    var option = $('<option></option>').val(coin.id).text(coin.name);
                    docFrag.append(option);
                }
            });
            $('#cmcCoinList').html(docFrag);
            
        });
    }

    $('#cmcCoinList').change(function(){
        var ticker = $(this).val();
        $.ajax({
            method: 'GET',
            url: '/trading_simulator/getCMCcoin/',
            data: {'ticker':ticker}
        }).done(function(msg){
            console.log(msg);
            $('#coinAdd tbody td:nth-child(2)').text(msg.data.name)
            $('#coinAdd tbody td:nth-child(3)').text(msg.data.symbol)
            $('#coinAdd tbody td:nth-child(4)').text(msg.data.id)
        });
    });

    $('#btnAddCoin').click(function(){
        var name = $('#coinAdd tbody td:nth-child(2)').text()
        var symbol = $('#coinAdd tbody td:nth-child(3)').text()
        var cmcId = $('#coinAdd tbody td:nth-child(4)').text()
        $.ajax({
            method: 'POST',
            url: '/api/coin/',
            data: {'name':name, 'symbol':symbol, 'cmcId':cmcId}
        }).done(function(msg){
            console.log(msg)
            getCoins();
        });
    });

    $('#coinList>tbody').on('click', '.btnDeleteCoin', function(){
        var confirmDelete = confirm(`delete ${$(this).parent().parent().children('td:eq(1)').text()} from db?`);
        if(confirmDelete){
            var coinId = $(this).parent().parent().children('td:eq(0)').text();
            $.ajax({
                method: 'DELETE',
                url: '/api/coin/' + coinId + '/',
            }).done(function(msg){
                console.log(msg)
                getCoins();
            });
        }
    });

    function getAccounts(){
        $.ajax({
            method: 'GET',
            url: '/api/account/'
        }).done(function(msg){
            console.log(msg);
            $('#accountListTitle').text(`Account List (${msg.length} accounts total)`);
            var docFrag = $(document.createDocumentFragment());
            $.each(msg, function(index, account){
                var row = $('<tr></tr>');
                var accountId = $('<td></td>').html(account.accountId);
                var name = $('<td></td>').html(account.name).attr('contenteditable','true');
                var email = $('<td></td>').html(account.email).attr('contenteditable','true');
                var edit = $('<td></td>').html('<button class="btnEditAccount btn btn-secondary"><i class="fas fa-user-edit"></i></button><button class="btnDeleteAccount btn btn-danger"><i class="fas fa-trash"></i></button>');
                row.append([accountId, name, email, edit]);
                docFrag.append(row);
            });
            $('#accountList tbody').html(docFrag);
        });
    }
    getAccounts();

    $('#accountList>tbody').on('click', '.btnDeleteAccount', function(){
        var confirmDelete = confirm(`delete ${$(this).parent().parent().children('td:eq(1)').text()}'s account from db?'`);
        if(confirmDelete) {
            var accountId = $(this).parent().parent().children('td:eq(0)').text();
            $.ajax({
                method: 'DELETE',
                url: '/api/account/' + accountId + '/',
            }).done(function(msg){
                console.log(msg)
                getAccounts();
            });
        }
    });
    
    $('#accountList>tbody').on('click', '.btnEditAccount', function(){
        var accountId = $(this).parent().parent().children('td:eq(0)').text();
        var name = $(this).parent().parent().children('td:eq(1)').text();
        var email = $(this).parent().parent().children('td:eq(2)').text();
        var data = {
            "name":name, 
            "email":email
        };
        
        $.ajax({
            method: 'GET',
            url: '/trading_simulator/validateEmail?email='+email,
        }).done(function(msg){
            if(msg.length == 0){
                $.ajax({
                    method: 'PATCH',
                    url: '/api/account/' + accountId + '/',
                    'data': data
                }).done(function(msg){
                    console.log(msg)
                    getAccounts();
                }).fail(function(msg){
                    console.log(msg)
                    alert(msg.responseText)
                    getAccounts();
                });
            } else {
                alert("email already in use");
            }
        })
    });
    
    // TO TOP
    $('#btnToTop').click(topFunction);
    window.onscroll = function() {scrollFunction()};

    function scrollFunction() {
        if (document.body.scrollTop > 200 || document.documentElement.scrollTop > 200) {
            document.getElementById("btnToTop").style.display = "block";
            $('#btnToTop').fadeTo(500, 0.8);
        } else {
            document.getElementById("btnToTop").style.display = "none";
        }
    }

    function topFunction() {
        $('html, body').animate({ scrollTop: 0 }, 'slow');
        $(this).fadeTo(500, 0);
    }
    // END TO TOP
</script>
{% endblock %}

trading_simulator/templates/trading_simulator/create.html
{% extends 'base.html' %}
{% block content %}
{% include 'trading_simulator/nav.html' %}
<div class="container">
    <div class="row align-items-center" style="margin:100px 0;">
        <div class="col-md-6 col-md-offset-6 mx-auto">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Create account</h3>
                </div>
                
                <form id="create" method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" name="name" id="name" placeholder="enter a name">
                    </div>
                    <div class="form-group">
                        <label for="email">Email address</label>
                        <input type="email" class="form-control" name="email" id="email" placeholder="enter an email address">
                        <span id="emailHint"></span>
                    </div>
                    <div class="form-group">
                        <label for="pwd">Password</label>
                        <input type="password" class="form-control" name="password" id="pwd" placeholder="enter a password">
                        <span id="pwdHint"></span>
                    </div>
                    <div class="form-group">
                        <label for="initial">Initial USD balance</label>
                        <input type="number" class="form-control" name="initial" id="initial" placeholder="set an initial USD balance">
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-4 mx-auto">
                            <input type="submit" id="submit" class="btn btn-primary form-control" value="Submit">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    $('#create').submit(function(event) {
        let initial = parseFloat($('#initial').val());
        
        if(initial < 0 || isNaN(initial)) {
            alert("enter an initial balance");
        } else if(!checkName()) {
            alert("enter a name");
        } else if(!checkEmail()) {
            alert("enter an email address");
        } else if(!checkPassword()) {
            alert("enter a password");
        } else {
            return;
        }

        event.preventDefault();
    });
    
    function checkName(){
        return $('#name').val() ? true : false;
    }

    function checkEmail(){
        return $('#email').val() ? true : false;
    }

    function checkPassword(){
        return $('#pwd').val() ? true : false;
    }

    $('#name').on('input', function(){
        if($(this).val()!=''){
            $(this).attr('style', 'border: 2px solid #0069d9');
        } else {
            $(this).attr('style', 'border: 2px solid #c82333');
        }
    });

    $('#email').on('input', function(){
        $('#emailHint').text("");
        $.ajax({
            method: "GET",
            url: `/trading_simulator/validateEmail?email=${$(this).val()}`
        })
        .done(function(msg){
            console.log(msg);
            if(msg.length==0 && $('#email').val()!='' && /\w+@\w+\.\w+/.test($('#email').val())){
                $('#email').attr('style', 'border: 2px solid #0069d9');
            } else if(msg.length > 0){
                $('#emailHint').text("email is in use, choose another");
                $('#email').attr('style', 'border: 2px solid #c82333');
            } else if($('#email').val()=='') {
                $('#email').attr('style', 'border: 2px solid #c82333');
            } else {
                $('#email').attr('style', 'border: 2px solid #c82333');
            }
        });
    });

    $('#pwd').on('input', function(){
        $('#pwdHint').text("");
        if($(this).val()!='' && /.{4,}/.test($(this).val())){
            $(this).attr('style', 'border: 2px solid #0069d9');
        } else {
            $('#pwdHint').text("password too short");
            $(this).attr('style', 'border: 2px solid #c82333');
        }
    });

    $('#initial').on('input', function(){
        let value = $(this).val();
        if($(this).val()!='' && value > 0){
            $(this).attr('style', 'border: 2px solid #0069d9');
        } else {
            $(this).attr('style', 'border: 2px solid #c82333');
        }
    });
</script>
{% endblock %}

trading_simulator/templates/trading_simulator/deposit.html
{% extends 'base.html' %}
{% block content %}
{% include 'trading_simulator/nav.html' %}
    <h1>deposit</h1>
    <form method="POST" autocomplete="off">
        {% csrf_token %}
        <div class="form-group">
            <label for="usd">USD</label>
            <input type="text" class="form-control" name="usd" id="usd" value="{{ balance_.USDbalance }}"> 
        </div>
        <div class="form-group">
            <label for="btc">BTC</label>
            <input type="text" class="form-control" name="btc" id="btc" value="{{ balance_.BTCbalance }}"> 
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</body>
{% endblock %}

trading_simulator/templates/trading_simulator/index.html
{% extends 'base.html' %}
{% block content %}

{% include 'trading_simulator/nav.html' %}
    <!-- <h1>Trading Simulator</h1>
    {% if request.COOKIES.email %}
    <h2>hello {{ request.COOKIES.email }}</h2>
    {% else %}
    <h2>hello guest, please login</h2>
    {% endif %} -->
{% endblock %}

trading_simulator/templates/trading_simulator/login.html
{% extends 'base.html' %}
{% block content %}
{% include 'trading_simulator/nav.html' %}
<div class="container">
    <div class="row align-items-center" style="margin:100px 0;">
        <div class="col-md-4 col-md-offset-4 mx-auto">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Sign in to your account</h3>
                </div>
             
                <form method="POST" autocomplete="off">
                    {% csrf_token %}
                    <div class="form-group">
                        <!-- <label for="email">Email address</label> -->
                        <input type="email" class="form-control" name="email" id="email" placeholder="Email address">
                    </div>
                    <div class="form-group">
                        <!-- <label for="pwd">Password</label> -->
                        <input type="password" class="form-control" name="password" id="pwd" placeholder="Password">
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-4 mx-auto">
                            <button type="submit" class="btn btn-primary form-control">Login</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>  
{% endblock %}

trading_simulator/templates/trading_simulator/nav.html
<div class="jumbotron">
    <h1 class="display-3">Trading Simulator</h1>

    {% if request.COOKIES.email %}
    <p class="lead">Logged in as: {{ request.COOKIES.email }}.</p>
    {% else %}
    <p class="lead">Hello guest, please login to start trading.</p>
    {% endif %}

    <hr class="my-4">
    <div class="btn-group" role="group" aria-label="Basic example">
        {% if request.COOKIES.email %}
            <!-- <a href="{% url 'trading_simulator:deposit' request.COOKIES.accountId %}" class="btn btn-primary btn-lg px-5">Deposit</a> -->
            <a href="{% url 'trading_simulator:trading' request.COOKIES.accountId %}" class="btn btn-primary btn-lg px-5">Trade</a>
            <a href="{% url 'trading_simulator:balances' request.COOKIES.accountId %}" class="btn btn-primary btn-lg px-5">Account Overview</a>
            <a href="/trading_simulator/logout/" class="btn btn-primary btn-lg px-5">Logout</a>
        {% else %}
            <a href="{% url 'trading_simulator:create' %}" class="btn btn-primary btn-lg px-5">Create Account</a>
            <a href="{% url 'trading_simulator:login' %}" class="btn btn-primary btn-lg px-5">Login</a>
        {% endif %}
    </div>
</div>